### ISSUE TITLE
Trailing slash

### ISSUE THREAD

**Issue by peleteiro** [krakenjs/reverend#7]
IMHO, reverend should remove trailing slash. Cases like `reverend('/user/:id/:operation?', { id: 5 })` should be `/user/5` and not `/user/5/`. In cases like  `reverend('/user/:id/:operation?/', { id: 5 })` should be `/user/5/`.

What do you guys think?

**Comment by totherik** [comment]
Thanks @peleteiro. Sorry, it has been a while since I took a look at this. Is the behavior you're observing that a trailing slash is *always* included in the result, regardless of whether or not it's in the source?

**Comment by peleteiro** [comment]
Yes, in current version `reverend('/user/:id/:operation?', { id: 5 })` results in `/users/5/`, but `reverend('/user/:id/:operation?', {id: 5, operation: 123})` results in `/users/5/123`.

**Comment by jasisk** [comment]
Hey @peleteiro. Interesting idea. I'm gonna keep this open while I think on it but I'm inclined to agree this behavior is the appropriate inverse of the route matching behavior.

**Comment by jasisk** [comment]
Closed by #9.
