### ISSUE TITLE
Compiling to path now supported with Path-To-RegExp >= 1.1.0

### ISSUE THREAD

**Issue by blakeembrey** [krakenjs/reverend#8]
I was linked to this library recently and wanted to let you know this functionality has been baked into the latest version of `path-to-regexp`. I'd love if you could take a look at https://github.com/pillarjs/path-to-regexp#compile-reverse-path-to-regexp and the implementation to see if it's how you expect it to work, then maybe we can look at migrating any tools using this library. I noticed that the baked in functionality should handle the issue you have around the trailing slash.

**Comment by totherik** [comment]
This is great, thanks @blakeembrey! @jasisk and I will take a look, but I'm excited deprecate this in favor of path-to-regexp.

**Comment by jasisk** [comment]
Big :+1: from me. I guess we probably could have upstreamed this behavior, ourselves. Oops. :grinning: 

I'll take a look today to make sure things move over seamlessly but, pending that, I'm 100% in favor of deprecating reverend. I'll open an issue with a task list.

Thanks for the heads-up, @blakeembrey.

**Comment by jasisk** [comment]
Closed by #9.
