### ISSUE TITLE
Deprecate Reverend in favor of path-to-regexp

### ISSUE THREAD

**Issue by jasisk** [krakenjs/reverend#9]
- [x] Shim Reverend to use path-to-regexp under the hood (b6fabd263acdd0620cc41cc265478344469311f5)
- [x] Write tests for new functionality (trailing slash, etc) (c056da781b12b7862a554f63346fcc0f4e0ffd50)
- [x] Ensure existing test suite passes (b6fabd263acdd0620cc41cc265478344469311f5)
- [x] Ensure shimmed Reverend functions in dependents:  
✓ `express-enrouten`, ✓ `routr`, ✓ `fixturl`, ✓ `pathematics`, ✓ `static-engine-render`
- [x] Readme changes to document deprecation (abb56d3915bb0c0ee2f7f4ff157b9a2e2e174801)
- [x] Remove Reverend from dependents:  
✓ [`express-enrouten`](https://github.com/krakenjs/express-enrouten/pull/70), ✓ [`routr`](https://github.com/yahoo/routr/pull/23), — [`fixturl`](https://github.com/indieisaconcept/fixturl/pull/2), — [`pathematics`](https://github.com/scottcorgan/pathematics/pull/2), — [`static-engine-render`](https://github.com/erickmerchant/static-engine-render/pull/1)
- [x] Publish patch release with deprecation warning
- [x] Deprecate in npm

As per #8.

**Comment by jasisk** [comment]
All done here. Bye `Reverend`. :crying_cat_face:

**Comment by blakeembrey** [comment]
Amazing work! :+1:

**Comment by jasisk** [comment]
Thanks! And thanks for adding the functionality upstream.

**Comment by mridgway** [comment]
Thanks for your work on this!
